app = "kulturnatt-profile"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[[checks]]
  name = "health"
  port = 8001
  type = "http"
  method = "GET"
  path = "/health"
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
